require "./config/version"
require "./lib/cli"
require "./lib/scraper"
require "./lib/download"
require "./lib/theme"
require "./lib/vectors"
require "./lib/dl_queue"

require "nokogiri"
require "open-uri"
require "pry"